//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.RegisterLoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterLoginServiceReference.RegisterLoginWSSoap")]
    public interface RegisterLoginWSSoap {
        
        // CODEGEN: Generating message contract since element name supplierId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerSupplier", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.registerSupplierResponse registerSupplier(ClientApplication.RegisterLoginServiceReference.registerSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerSupplierResponse> registerSupplierAsync(ClientApplication.RegisterLoginServiceReference.registerSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name warehouseStaffId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerWarehouseStaff", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse registerWarehouseStaff(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerWarehouseStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse> registerWarehouseStaffAsync(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest request);
        
        // CODEGEN: Generating message contract since element name pharmacyStaffId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerPharmacyStaff", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse registerPharmacyStaff(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerPharmacyStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse> registerPharmacyStaffAsync(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest request);
        
        // CODEGEN: Generating message contract since element name AutoSupplierIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSupplierId", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse AutoSupplierId(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoSupplierId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse> AutoSupplierIdAsync(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest request);
        
        // CODEGEN: Generating message contract since element name AutoWarehouseStaffIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoWarehouseStaffId", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse AutoWarehouseStaffId(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoWarehouseStaffId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse> AutoWarehouseStaffIdAsync(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest request);
        
        // CODEGEN: Generating message contract since element name AutoPharmacyStaffIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyStaffId", ReplyAction="*")]
        ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse AutoPharmacyStaffId(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPharmacyStaffId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse> AutoPharmacyStaffIdAsync(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerSupplier", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerSupplierRequestBody Body;
        
        public registerSupplierRequest() {
        }
        
        public registerSupplierRequest(ClientApplication.RegisterLoginServiceReference.registerSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string supplierId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string supplierName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string supCompanyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telephone;
        
        public registerSupplierRequestBody() {
        }
        
        public registerSupplierRequestBody(string supplierId, string supplierName, string supCompanyName, string email, string telephone) {
            this.supplierId = supplierId;
            this.supplierName = supplierName;
            this.supCompanyName = supCompanyName;
            this.email = email;
            this.telephone = telephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerSupplierResponseBody Body;
        
        public registerSupplierResponse() {
        }
        
        public registerSupplierResponse(ClientApplication.RegisterLoginServiceReference.registerSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registerSupplierResult;
        
        public registerSupplierResponseBody() {
        }
        
        public registerSupplierResponseBody(string registerSupplierResult) {
            this.registerSupplierResult = registerSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerWarehouseStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerWarehouseStaff", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequestBody Body;
        
        public registerWarehouseStaffRequest() {
        }
        
        public registerWarehouseStaffRequest(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerWarehouseStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string warehouseStaffId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string warehouseEmployeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string warehouseUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string warehousePassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string warehouseUserType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string warehouseEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string warehouseTelephone;
        
        public registerWarehouseStaffRequestBody() {
        }
        
        public registerWarehouseStaffRequestBody(string warehouseStaffId, string warehouseEmployeeName, string warehouseUsername, string warehousePassword, string warehouseUserType, string warehouseEmail, string warehouseTelephone) {
            this.warehouseStaffId = warehouseStaffId;
            this.warehouseEmployeeName = warehouseEmployeeName;
            this.warehouseUsername = warehouseUsername;
            this.warehousePassword = warehousePassword;
            this.warehouseUserType = warehouseUserType;
            this.warehouseEmail = warehouseEmail;
            this.warehouseTelephone = warehouseTelephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerWarehouseStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerWarehouseStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponseBody Body;
        
        public registerWarehouseStaffResponse() {
        }
        
        public registerWarehouseStaffResponse(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerWarehouseStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registerWarehouseStaffResult;
        
        public registerWarehouseStaffResponseBody() {
        }
        
        public registerWarehouseStaffResponseBody(string registerWarehouseStaffResult) {
            this.registerWarehouseStaffResult = registerWarehouseStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerPharmacyStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerPharmacyStaff", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequestBody Body;
        
        public registerPharmacyStaffRequest() {
        }
        
        public registerPharmacyStaffRequest(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerPharmacyStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pharmacyStaffId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pharmacyEmployeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pharmacyUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pharmacyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pharmacyUserType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pharmacyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pharmacyBranch;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pharmacyEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pharmacyTelephone;
        
        public registerPharmacyStaffRequestBody() {
        }
        
        public registerPharmacyStaffRequestBody(string pharmacyStaffId, string pharmacyEmployeeName, string pharmacyUsername, string pharmacyPassword, string pharmacyUserType, string pharmacyName, string pharmacyBranch, string pharmacyEmail, string pharmacyTelephone) {
            this.pharmacyStaffId = pharmacyStaffId;
            this.pharmacyEmployeeName = pharmacyEmployeeName;
            this.pharmacyUsername = pharmacyUsername;
            this.pharmacyPassword = pharmacyPassword;
            this.pharmacyUserType = pharmacyUserType;
            this.pharmacyName = pharmacyName;
            this.pharmacyBranch = pharmacyBranch;
            this.pharmacyEmail = pharmacyEmail;
            this.pharmacyTelephone = pharmacyTelephone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerPharmacyStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerPharmacyStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponseBody Body;
        
        public registerPharmacyStaffResponse() {
        }
        
        public registerPharmacyStaffResponse(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerPharmacyStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registerPharmacyStaffResult;
        
        public registerPharmacyStaffResponseBody() {
        }
        
        public registerPharmacyStaffResponseBody(string registerPharmacyStaffResult) {
            this.registerPharmacyStaffResult = registerPharmacyStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSupplierIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSupplierId", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequestBody Body;
        
        public AutoSupplierIdRequest() {
        }
        
        public AutoSupplierIdRequest(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoSupplierIdRequestBody {
        
        public AutoSupplierIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoSupplierIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoSupplierIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponseBody Body;
        
        public AutoSupplierIdResponse() {
        }
        
        public AutoSupplierIdResponse(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSupplierIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoSupplierIdResult;
        
        public AutoSupplierIdResponseBody() {
        }
        
        public AutoSupplierIdResponseBody(string AutoSupplierIdResult) {
            this.AutoSupplierIdResult = AutoSupplierIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoWarehouseStaffIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoWarehouseStaffId", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequestBody Body;
        
        public AutoWarehouseStaffIdRequest() {
        }
        
        public AutoWarehouseStaffIdRequest(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoWarehouseStaffIdRequestBody {
        
        public AutoWarehouseStaffIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoWarehouseStaffIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoWarehouseStaffIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponseBody Body;
        
        public AutoWarehouseStaffIdResponse() {
        }
        
        public AutoWarehouseStaffIdResponse(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoWarehouseStaffIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoWarehouseStaffIdResult;
        
        public AutoWarehouseStaffIdResponseBody() {
        }
        
        public AutoWarehouseStaffIdResponseBody(string AutoWarehouseStaffIdResult) {
            this.AutoWarehouseStaffIdResult = AutoWarehouseStaffIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyStaffIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyStaffId", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequestBody Body;
        
        public AutoPharmacyStaffIdRequest() {
        }
        
        public AutoPharmacyStaffIdRequest(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AutoPharmacyStaffIdRequestBody {
        
        public AutoPharmacyStaffIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutoPharmacyStaffIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutoPharmacyStaffIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponseBody Body;
        
        public AutoPharmacyStaffIdResponse() {
        }
        
        public AutoPharmacyStaffIdResponse(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoPharmacyStaffIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AutoPharmacyStaffIdResult;
        
        public AutoPharmacyStaffIdResponseBody() {
        }
        
        public AutoPharmacyStaffIdResponseBody(string AutoPharmacyStaffIdResult) {
            this.AutoPharmacyStaffIdResult = AutoPharmacyStaffIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegisterLoginWSSoapChannel : ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterLoginWSSoapClient : System.ServiceModel.ClientBase<ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap>, ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap {
        
        public RegisterLoginWSSoapClient() {
        }
        
        public RegisterLoginWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterLoginWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterLoginWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterLoginWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.registerSupplierResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerSupplier(ClientApplication.RegisterLoginServiceReference.registerSupplierRequest request) {
            return base.Channel.registerSupplier(request);
        }
        
        public string registerSupplier(string supplierId, string supplierName, string supCompanyName, string email, string telephone) {
            ClientApplication.RegisterLoginServiceReference.registerSupplierRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerSupplierRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            inValue.Body.supplierName = supplierName;
            inValue.Body.supCompanyName = supCompanyName;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            ClientApplication.RegisterLoginServiceReference.registerSupplierResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerSupplier(inValue);
            return retVal.Body.registerSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerSupplierResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerSupplierAsync(ClientApplication.RegisterLoginServiceReference.registerSupplierRequest request) {
            return base.Channel.registerSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerSupplierResponse> registerSupplierAsync(string supplierId, string supplierName, string supCompanyName, string email, string telephone) {
            ClientApplication.RegisterLoginServiceReference.registerSupplierRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerSupplierRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerSupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            inValue.Body.supplierName = supplierName;
            inValue.Body.supCompanyName = supCompanyName;
            inValue.Body.email = email;
            inValue.Body.telephone = telephone;
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerWarehouseStaff(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest request) {
            return base.Channel.registerWarehouseStaff(request);
        }
        
        public string registerWarehouseStaff(string warehouseStaffId, string warehouseEmployeeName, string warehouseUsername, string warehousePassword, string warehouseUserType, string warehouseEmail, string warehouseTelephone) {
            ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequestBody();
            inValue.Body.warehouseStaffId = warehouseStaffId;
            inValue.Body.warehouseEmployeeName = warehouseEmployeeName;
            inValue.Body.warehouseUsername = warehouseUsername;
            inValue.Body.warehousePassword = warehousePassword;
            inValue.Body.warehouseUserType = warehouseUserType;
            inValue.Body.warehouseEmail = warehouseEmail;
            inValue.Body.warehouseTelephone = warehouseTelephone;
            ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerWarehouseStaff(inValue);
            return retVal.Body.registerWarehouseStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerWarehouseStaffAsync(ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest request) {
            return base.Channel.registerWarehouseStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffResponse> registerWarehouseStaffAsync(string warehouseStaffId, string warehouseEmployeeName, string warehouseUsername, string warehousePassword, string warehouseUserType, string warehouseEmail, string warehouseTelephone) {
            ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerWarehouseStaffRequestBody();
            inValue.Body.warehouseStaffId = warehouseStaffId;
            inValue.Body.warehouseEmployeeName = warehouseEmployeeName;
            inValue.Body.warehouseUsername = warehouseUsername;
            inValue.Body.warehousePassword = warehousePassword;
            inValue.Body.warehouseUserType = warehouseUserType;
            inValue.Body.warehouseEmail = warehouseEmail;
            inValue.Body.warehouseTelephone = warehouseTelephone;
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerWarehouseStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerPharmacyStaff(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest request) {
            return base.Channel.registerPharmacyStaff(request);
        }
        
        public string registerPharmacyStaff(string pharmacyStaffId, string pharmacyEmployeeName, string pharmacyUsername, string pharmacyPassword, string pharmacyUserType, string pharmacyName, string pharmacyBranch, string pharmacyEmail, string pharmacyTelephone) {
            ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequestBody();
            inValue.Body.pharmacyStaffId = pharmacyStaffId;
            inValue.Body.pharmacyEmployeeName = pharmacyEmployeeName;
            inValue.Body.pharmacyUsername = pharmacyUsername;
            inValue.Body.pharmacyPassword = pharmacyPassword;
            inValue.Body.pharmacyUserType = pharmacyUserType;
            inValue.Body.pharmacyName = pharmacyName;
            inValue.Body.pharmacyBranch = pharmacyBranch;
            inValue.Body.pharmacyEmail = pharmacyEmail;
            inValue.Body.pharmacyTelephone = pharmacyTelephone;
            ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerPharmacyStaff(inValue);
            return retVal.Body.registerPharmacyStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.registerPharmacyStaffAsync(ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest request) {
            return base.Channel.registerPharmacyStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffResponse> registerPharmacyStaffAsync(string pharmacyStaffId, string pharmacyEmployeeName, string pharmacyUsername, string pharmacyPassword, string pharmacyUserType, string pharmacyName, string pharmacyBranch, string pharmacyEmail, string pharmacyTelephone) {
            ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest inValue = new ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.registerPharmacyStaffRequestBody();
            inValue.Body.pharmacyStaffId = pharmacyStaffId;
            inValue.Body.pharmacyEmployeeName = pharmacyEmployeeName;
            inValue.Body.pharmacyUsername = pharmacyUsername;
            inValue.Body.pharmacyPassword = pharmacyPassword;
            inValue.Body.pharmacyUserType = pharmacyUserType;
            inValue.Body.pharmacyName = pharmacyName;
            inValue.Body.pharmacyBranch = pharmacyBranch;
            inValue.Body.pharmacyEmail = pharmacyEmail;
            inValue.Body.pharmacyTelephone = pharmacyTelephone;
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).registerPharmacyStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoSupplierId(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest request) {
            return base.Channel.AutoSupplierId(request);
        }
        
        public string AutoSupplierId() {
            ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequestBody();
            ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoSupplierId(inValue);
            return retVal.Body.AutoSupplierIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoSupplierIdAsync(ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest request) {
            return base.Channel.AutoSupplierIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoSupplierIdResponse> AutoSupplierIdAsync() {
            ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoSupplierIdRequestBody();
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoSupplierIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoWarehouseStaffId(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest request) {
            return base.Channel.AutoWarehouseStaffId(request);
        }
        
        public string AutoWarehouseStaffId() {
            ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequestBody();
            ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoWarehouseStaffId(inValue);
            return retVal.Body.AutoWarehouseStaffIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoWarehouseStaffIdAsync(ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest request) {
            return base.Channel.AutoWarehouseStaffIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdResponse> AutoWarehouseStaffIdAsync() {
            ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoWarehouseStaffIdRequestBody();
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoWarehouseStaffIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoPharmacyStaffId(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest request) {
            return base.Channel.AutoPharmacyStaffId(request);
        }
        
        public string AutoPharmacyStaffId() {
            ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequestBody();
            ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse retVal = ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoPharmacyStaffId(inValue);
            return retVal.Body.AutoPharmacyStaffIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse> ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap.AutoPharmacyStaffIdAsync(ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest request) {
            return base.Channel.AutoPharmacyStaffIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdResponse> AutoPharmacyStaffIdAsync() {
            ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest inValue = new ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequest();
            inValue.Body = new ClientApplication.RegisterLoginServiceReference.AutoPharmacyStaffIdRequestBody();
            return ((ClientApplication.RegisterLoginServiceReference.RegisterLoginWSSoap)(this)).AutoPharmacyStaffIdAsync(inValue);
        }
    }
}
