//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.AddUpdateSearchStockServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddUpdateSearchStockServiceReference.StockWSSoap")]
    public interface StockWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addStock(string stockId, string drugName, string drugCategory, string drugBrnad, int quantity, string suitabiliy, string supplierName, string supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addStock", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addStockAsync(string stockId, string drugName, string drugCategory, string drugBrnad, int quantity, string suitabiliy, string supplierName, string supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchStock(string stockId, string drugName, string drugCategory, string drugBrand, string suitability, string supplierName, string supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchStock", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchStockAsync(string stockId, string drugName, string drugCategory, string drugBrand, string suitability, string supplierName, string supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoStockId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoStockId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoStockId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoStockIdAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockWSSoapChannel : ClientApplication.AddUpdateSearchStockServiceReference.StockWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockWSSoapClient : System.ServiceModel.ClientBase<ClientApplication.AddUpdateSearchStockServiceReference.StockWSSoap>, ClientApplication.AddUpdateSearchStockServiceReference.StockWSSoap {
        
        public StockWSSoapClient() {
        }
        
        public StockWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addStock(string stockId, string drugName, string drugCategory, string drugBrnad, int quantity, string suitabiliy, string supplierName, string supplierId) {
            return base.Channel.addStock(stockId, drugName, drugCategory, drugBrnad, quantity, suitabiliy, supplierName, supplierId);
        }
        
        public System.Threading.Tasks.Task<string> addStockAsync(string stockId, string drugName, string drugCategory, string drugBrnad, int quantity, string suitabiliy, string supplierName, string supplierId) {
            return base.Channel.addStockAsync(stockId, drugName, drugCategory, drugBrnad, quantity, suitabiliy, supplierName, supplierId);
        }
        
        public System.Data.DataSet searchStock(string stockId, string drugName, string drugCategory, string drugBrand, string suitability, string supplierName, string supplierId) {
            return base.Channel.searchStock(stockId, drugName, drugCategory, drugBrand, suitability, supplierName, supplierId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchStockAsync(string stockId, string drugName, string drugCategory, string drugBrand, string suitability, string supplierName, string supplierId) {
            return base.Channel.searchStockAsync(stockId, drugName, drugCategory, drugBrand, suitability, supplierName, supplierId);
        }
        
        public string AutoStockId() {
            return base.Channel.AutoStockId();
        }
        
        public System.Threading.Tasks.Task<string> AutoStockIdAsync() {
            return base.Channel.AutoStockIdAsync();
        }
    }
}
